### ISSUE TITLE
UIN.pm needs to be migrated to NeuLevel Narwhal

### ISSUE THREAD

**Issue by incubatec** [thedarkwinter/Net-DRI#269]
UIN is required for the registration (and explicit renewal) of .TRAVEL domain names, but currently the code resides only in the "old" NeuLevel branch and should be migrated to Narwhal since .TRAVEL was migrated by the Registry to Narwhal a few days ago, too.

**Comment by thedarkwinter** [comment]
Hi. The preferred method going forward is to use the KeyValue extension instead of UIN (neulevel). The old extension (using <unspec>) can still be used by adding to profile as the example in [UIN.t](https://github.com/thedarkwinter/Net-DRI/blob/master/t/Net/DRI/Protocol/EPP/Extensions/NeuLevel/UIN.t). See [KeyValue.t](https://github.com/thedarkwinter/Net-DRI/blob/master/t/Net/DRI/Protocol/EPP/Extensions/NeuLevel/KeyValue.t) for renewal example using new extension. Let me know if this doesn't make sense of if you have any issues as I haven't tested either in a production environment. (BTW, this was updated today).

Cheers,
Michael
