### ISSUE TITLE
.eu poll-1.2

### ISSUE THREAD

**Issue by thedarkwinter** [thedarkwinter/Net-DRI#66]
http://www.eurid.eu/xml/epp/poll-1.2 is not getting parsed
4:Assert failed: EPP::parse_poll was not able to parse anything, please report

**Comment by thedarkwinter** [comment]
https://github.com/thedarkwinter/Net-DRI/commit/1a32c0fb59ff21f16ad5211c40b9fcb2a6c6c702

still got other updated to do tho

**Comment by thedarkwinter** [comment]
this was done in here, and some subsequent work completed it https://github.com/thedarkwinter/Net-DRI/commit/1a32c0fb59ff21f16ad5211c40b9fcb2a6c6c702

**Comment by incubatec** [comment]
When trying to create a contact for .NAME domain registrations using the VeriSign::NameStore module, the following error is given via EPP:

`<?xml version="1.0" encoding="UTF-8"?><epp xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:ietf:params:xml:ns:epp-1.0 epp-1.0.xsd" xmlns="urn:ietf:params:xml:ns:epp-1.0"><response><result code="2306"><msg>Parameter value policy error</msg><extValue><value xmlns:epp="urn:ietf:params:xml:ns:epp-1.0"><epp:undef/></value><reason>Service: DOTCOM not found</reason></extValue></result><trID><clTRID>VERISIGN::NAMESTORE-8882-1549037835544049</clTRID><svTRID>1549037835614-620386828</svTRID></trID></response></epp>`

The request XML is create as follows by Net::DRI:
`<?xml version="1.0" encoding="UTF-8" standalone="no"?><epp xmlns="urn:ietf:params:xml:ns:epp-1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:ietf:params:xml:ns:epp-1.0 epp-1.0.xsd"><command><create><contact:create xmlns:contact="urn:ietf:params:xml:ns:contact-1.0" xsi:schemaLocation="urn:ietf:params:xml:ns:contact-1.0 contact-1.0.xsd"><contact:id>123</contact:id><contact:postalInfo type="loc"><contact:name>John Doe</contact:name><contact:org>Megaorg</contact:org><contact:addr><contact:street>Via Marte 11</contact:street><contact:street/><contact:street/><contact:city>Borgo Fantasia</contact:city><contact:sp>BZ</contact:sp><contact:pc>39100</contact:pc><contact:cc>IT</contact:cc></contact:addr></contact:postalInfo><contact:voice>+39.0123456789</contact:voice><contact:email>blackhole@blackhole.cloud</contact:email><contact:authInfo><contact:pw>S0M3R@Nd0MPwD</contact:pw></contact:authInfo></contact:create></create><extension><namestoreExt:namestoreExt xmlns:namestoreExt="http://www.verisign-grs.com/epp/namestoreExt-1.1" xsi:schemaLocation="http://www.verisign-grs.com/epp/namestoreExt-1.1 namestoreExt-1.1.xsd"><namestoreExt:subProduct>dotCOM</namestoreExt:subProduct></namestoreExt:namestoreExt></extension><clTRID>VERISIGN::NAMESTORE-8882-1549037835544049</clTRID></command></epp>`

The problem is that it should not automatically specifcy "dotCOM" as sub-product:
<namestoreExt:subProduct>dotCOM</namestoreExt:subProduct>
and instead use
<namestoreExt:subProduct>dotNAME</namestoreExt:subProduct>
to get the correct results. This can be achieved by forcing the $ext variable in Net/DRI/Protocol/EPP/Extensions/VeriSign/NameStore.pm to "name", but that probably will cause issues e.g. for .COM domains thereafter.

Any ideas on how to solve this without completely separating the extensions?
